#lang info
(define collection "scribble-rainbow-delimiters")
(define deps '("base" "scribble-lib"))
(define build-deps '("scribble-lib" "racket-doc" "rackunit-lib"))
(define scribblings '(("scribblings/scribble-rainbow-delimiters.scrbl" () ("Scribble Libraries"))))
(define pkg-desc "Colorizing matched brackets of codes on HTML pages generated by Racket Scribble.")
(define version "0.1")
(define pkg-authors '("Yanying Wang"))
